import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { Container, Button, Center } from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Center flexDirection={'column'}>
          <div
            className={styles.center}
            style={{
              fontFamily: 'monospace',
              fontSize: '6rem',
            }}
          >
            Xx_KarAIokI_xX
          </div>

          <Link href="/songSelect">
            <Button
              className="playbtn"
              colorScheme={'pink'}
              size="lg"
              py={70}
              fontSize="2rem"
              width="400px"
              borderRadius="20px"
            >
              Play!
            </Button>
          </Link>
        </Center>
      </Container>
    </>
  );
}
